# Generated by Django 3.2.4 on 2021-06-02 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HandleCSV', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='account_id',
            field=models.BigIntegerField(verbose_name='Account ID'),
        ),
        migrations.AlterField(
            model_name='account',
            name='content',
            field=models.JSONField(verbose_name='Content'),
        ),
        migrations.AlterField(
            model_name='account',
            name='created_at',
            field=models.DateTimeField(verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='account',
            name='modified_at',
            field=models.DateTimeField(verbose_name='Modified At'),
        ),
        migrations.AlterField(
            model_name='account',
            name='timestamp',
            field=models.DateTimeField(verbose_name='Timestamp'),
        ),
    ]
